### ISSUE TITLE
Ubuntu on Windows WSL does not have tcp congestion.

### ISSUE THREAD

**Issue by robert-andrzejuk** [esnet/iperf#1061]
# Context
Using Microsoft Store - Ubuntu, is installed (20.04LTS)
Installing iperf3 with "sudo apt-get install iperf3"

* Version of iperf3:
version 3.7-3

* Operating system (and distribution, if any):
Ubuntu on Windows (20.04 LTS)

# Bug Report
When running: `iperf3 -c XXXX` an error occurs:
iperf3: error - unable to set TCP_CONGESTION: Supplied congestion control algorithm not supported on this host

* Expected Behavior
iperf3 runs without error

* Actual Behavior

* Steps to Reproduce

* Possible Solution
A build on Ubuntu on Windows should have the `HAVE_TCP_CONGESTION` undef'ed.

**Comment by bmah888** [comment]
I'm afraid I don't completely understand the bug report...unless `XXXX` is a valid congestion control algorithm on Ubuntu on Windows, it's giving exactly the error message it should.  I'm not familiar with that runtime environment, but you might see if there's an equivalent to `sysctl net.ipv4.tcp_available_congestion_control` to list out what congestion control algorithms you have to choose from on that system.

If you meant `XXXX` as in everything you tried didn't work, note that the only way that `HAVE_TCP_CONGESTION` gets defined is if there's a `TCP_CONGESTION` socket option defined in the system headers (it's auto-detected at build time).  If Ubuntu on Windows defines that without actually implementing the socket option, then that's a bug of that environment, not iperf3 (or whatever other application).

**Comment by davidBar-On** [comment]
I am also using Windows WSL and I see that `/usr/include/netinet/tcp.h` includes:
```c
/*
 * User-settable options (used with setsockopt).
 */
......
#define TCP_CONGESTION       13 /* Congestion control algorithm.  */
.......
```

However, there is no `/proc/sys/net/ipv4/tcp_available_congestion_control` file.  Therefore, the test in `configure` for whether TCP Congestion is supported may need to be changed to support WSL.  E.g. change:
```sh
if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
  $EGREP "yes" >/dev/null 2>&1; then :
  iperf3_cv_header_tcp_congestion=yes
else
  iperf3_cv_header_tcp_congestion=no
fi
```

to something like:
```sh
if sysctl net.ipv4.tcp_available_congestion_control 2>&5 && (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
  $EGREP "yes" >/dev/null 2>&1; then :
  iperf3_cv_header_tcp_congestion=yes
else
  iperf3_cv_header_tcp_congestion=no
fi
```

**Comment by bmah888** [comment]
That breaks on FreeBSD unfortunately, which uses a different sysctl OID. Really the right way to check for the TCP congestion control setting functionality is via the header file, as currently done. It's unfortunate that some of these Windows-based UNIX-like environments don't support that functionality, but they really shouldn't be advertising (in the form of a header definition) something that the kernel doesn't.

The other thing that's often forgotten nowadays (and I do this sometimes too) is that the build and runtime environments might be configured differently. We really don't care if the build environment supports the TCP congestion algorithm selection or not because the code isn't necessarily going to run there. We do care if the runtime environment supports it, but we can't check there. So if it's possible to build the feature, we do so, and then we check at run-time by looking for an error return code when someone tries to set the congestion control algorithm and we do the setsockopt call.

Either way, the fact that WSL doesn't support this functionality means that iperf3 running there won't either. Also iperf3 will work just fine as long as the user doesn't try to use the `-c` flag, and even if she does, it errors out in a reasonably graceful way.

**Comment by bmah888** [comment]
https://github.com/esnet/iperf/issues/121#issuecomment-720198429

**Comment by CanadianJeff** [comment]
is upgrading to WSL2 required or can this be fixed to also support legact WSL1?

**Comment by Foxtaur** [comment]
The behavior I'm seeing doesn't match this statement:

> Also iperf3 will work just fine as long as the user doesn't try to use the -c flag, and even if she does, it errors out in a reasonably graceful way.

There might be confusion between the `-c` flag and the `-C` flag.  The original poster states `-c` [iperf3 acts as a client].  There also exists a `-C` flag [specify congestion algorithm], but from my reading of the report, that flag is not being specified, yet iperf3 still attempts to set some default value, and gives a fatal error.

Clearly iperf3 does not "error out in a graceful way," but instead treats the failure to set a congestion setting as a fatal error, and aborts.  This is really the behavior that's not desired:  Why not simply print a warning about inability to set the algorithm, and then proceed with the test?  Otherwise this tool simply can't be used on WSL1 through no fault of the end user.

**Comment by robert-andrzejuk** [comment]
@Foxtauer thank you for understanding the problem and putting it into sensible words.
@bmah888 "-c" is the "client" option, "XXX" is the client IP. The way it is now, makes it is unusable.

**Comment by davidBar-On** [comment]
Submitted PR #1126 that should fix the issue. Although I don't use WSL1 any more, I assume that the problem is that regardless of whether a congestion alg was set (using `-C` option), iperf3 is trying to get the used alg, and the failure is at that these points:
https://github.com/esnet/iperf/blob/de006004d4f431905cae311ddd2ca9a23b78669a/src/iperf_client_api.c#L86
and:
https://github.com/esnet/iperf/blob/de006004d4f431905cae311ddd2ca9a23b78669a/src/iperf_server_api.c#L607
The change is not to fail when the alg was not set by `-C` and instead setting the alg name to "unknown".

**Comment by bmah888** [comment]
OK.

**Comment by Drift91** [comment]
I'm still experiencing this issue on WSL1 even after purging the old package and downloading the master branch, building it and running `sudo make install`.

**Comment by neilbalch** [comment]
> I'm still experiencing this issue on WSL1 even after purging the old package and downloading the master branch, building it and running `sudo make install`.

Me too. I don't think this issue is actually closed...

**Comment by lackoffaithiffy** [comment]
> > I'm still experiencing this issue on WSL1 even after purging the old package and downloading the master branch, building it and running `sudo make install`.
> 
> Me too. I don't think this issue is actually closed...

Just hit the same wall.

**Comment by bmah888** [comment]
I can re-open this issue, but as a reminder, Windows is a platform that ESnet does not officially support. We don't have and will not have the resources to investigate this problem.

So someone in the community is going to have to come up with a pull request that fixes the problem. Those of you who are experiencing issues will need to provide some more information. At the very least the output from a run showing the command (with all arguments) and all of the output (including the error). Looking at the code from #1126, I think that having `--debug` set will help. Also having the output of `iperf3 --version` will help verify what version of code you're actually running.

**Comment by neilbalch** [comment]
@bmah888 Right, sorry for my original snarky reply without context. Here is what I'm doing on WSL:

```shell
neil@Neil-Legion:/mnt/c/Users/neilb$ iperf3 --version
iperf 3.7 (cJSON 1.5.2)
Linux Neil-Legion 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication
neil@Neil-Legion:/mnt/c/Users/neilb$ iperf3 --debug -c 192.168.1.23
send_parameters:
{
        "tcp":  true,
        "omit": 0,
        "time": 10,
        "parallel":     1,
        "len":  131072,
        "pacing_timer": 1000,
        "client_version":       "3.7"
}
Connecting to host 192.168.1.23, port 5201
SNDBUF is 524288, expecting 0
RCVBUF is 1048576, expecting 0
iperf3: error - unable to set TCP_CONGESTION: Supplied congestion control algorithm not supported on this host
neil@Neil-Legion:/mnt/c/Users/neilb$
```

And here's what I'm doing on the server side:

```shell
pi@RPi3B-NAS:~$ iperf3 --version
iperf 3.6 (cJSON 1.5.2)
Linux RPi3B-NAS 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication
pi@RPi3B-NAS:~$ iperf3 --debug -s
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
get_parameters:
{
        "tcp":  true,
        "omit": 0,
        "time": 10,
        "parallel":     1,
        "len":  131072,
        "pacing_timer": 1000,
        "client_version":       "3.7"
}
SNDBUF is 16384, expecting 0
RCVBUF is 131072, expecting 0
Accepted connection from 192.168.1.115, port 59751
Congestion algorithm is cubic
[  5] local 192.168.1.23 port 5201 connected to 192.168.1.115 port 59752
iperf3: the client has unexpectedly closed the connection
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
^Ciperf3: interrupt - the server has terminated
pi@RPi3B-NAS:~$
```

**Comment by bmah888** [comment]
@neilbalch No worries, everybody needs some snark in their life. ;-)

So let's see. It seems like iperf-3.7 on the client (which looks like it's the Windows WSL side). The fix in #1126 was merged around March 2021. So I think the earliest version of iperf3 that could have this fix is iperf-3.10, released in May 2021. The current release is iperf-3.10.1 (which is functionally identical to iperf-3.10):

https://downloads.es.net/pub/iperf/iperf-3.10.1.tar.gz

Could you give that a try? Alternatively, if you can `git clone` this respository, the tip of the `master` branch should have the fix (as of this writing it should report version `3.10.1+`). But I wouldn't expect version 3.7 (from June 2019) to handle the WSL case correctly.

**Comment by neilbalch** [comment]
Hrm, I see. Do I just `sudo make install` in the cloned directory, or is there some kind of purging I have to do to remove my current `iperf3` version?

**Comment by bmah888** [comment]
> 😁 Hrm, I see. Do I just `sudo make install` in the cloned directory, or is there some kind of purging I have to do to remove my current `iperf3` version?

I'm not 100% familiar with the WSL environment, but if you did `sudo make install` to get it there in the first place, doing that with the newer version should work.

Otherwise, assuming it's like Ubuntu Linux, you should be able to do something like `sudo apt remove iperf3` to get rid of the old one, then configure and compile iperf3, then `sudo make install`. (Probably in this order is best.)

Alternatively, if you want to test this without deinstalling/installing, you can run `src/iperf3 --version` (or whatever) from the top level of the repository you checked out (after building) and that should work too. This is what I usually do during development.

**Comment by neilbalch** [comment]
Ey! Looks like this is just down to `apt` having an out-of-date version of the `iperf3` package...

```shell
neil@Neil-Legion:~/iperf$ ./src/iperf3 -c 192.168.1.23
Connecting to host 192.168.1.23, port 5201
[  5] local 192.168.1.115 port 62875 connected to 192.168.1.23 port 5201
iperf3: getsockopt - Protocol not available
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  28.0 MBytes   235 Mbits/sec    0   36.0 Bytes
iperf3: getsockopt - Protocol not available
[  5]   1.00-2.00   sec  29.1 MBytes   244 Mbits/sec  538976288   6.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   2.00-3.00   sec  29.1 MBytes   245 Mbits/sec    0   6.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   3.00-4.00   sec  30.1 MBytes   253 Mbits/sec    0   0.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   4.00-5.00   sec  30.2 MBytes   254 Mbits/sec    0   6.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   5.00-6.00   sec  19.4 MBytes   163 Mbits/sec    0   6.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   6.00-7.00   sec   256 KBytes  2.10 Mbits/sec    0   0.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0   6.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   8.00-9.00   sec  4.25 MBytes  35.7 Mbits/sec    0   6.00 Bytes
iperf3: getsockopt - Protocol not available
[  5]   9.00-10.00  sec  29.1 MBytes   244 Mbits/sec  3756023563   0.00 Bytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   200 MBytes   167 Mbits/sec  32555             sender
[  5]   0.00-10.05  sec   200 MBytes   167 Mbits/sec                  receiver

iperf Done.
neil@Neil-Legion:~/iperf$
```

I guess the issue is actually resolved after all, for me at least. I can't speak to the experience of everyone else.

**Comment by bmah888** [comment]
Thanks for the follow-up @neilbalch ! OK I'll leave this issue open for a little while longer in case anyone else wants to chime in. If there aren't any other follow-ups by the end of the year I'll close it.

I think you might have uncovered a different bug with the `iperf3: getsockopt - Protocol not available` message. My guess is that the WSL (1?) environment doesn't support the `TCP_INFO` socket option either and it's barfing on that (but in a non-fatal way). That's probably a different issue though.
