### ISSUE TITLE
error - socket buffer size not set correctly

### ISSUE THREAD

**Issue by arainero** [esnet/iperf#757]
# Context

I am trying to do an iperf test from my machine 192.168.1.50 to another machine 192.168.1.220. The following test will give the error "error - socket buffer size not set correctly":

`iperf3 -c 192.168.1.220 -w 512K`

This command will work when -w is set to 416k, anything higher and that error is displayed. I did a little poking around and I thought it was due to my tcp session window being too small, but it doesn't appear to be the case.

These are some of the sysctl values:

```
net.core.rmem_max = 16777216
net.core.rmem_default = 212992
net.core.wmem_max = 212992
net.ipv4.tcp_rmem = 4096        87380   16777216
net.ipv4.tcp_wmem = 4096        16384   16777216
```

I am however able to do this test successfully in the other direction. So I believe this has to do with some type of setting on this machine, which I don't know what it may be. 

Any help will be appreciated on this.

Thank you!

* Version of iperf3:
iperf 3.1.7
Linux 3450asterisk 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing

* Hardware:
Onboard NIC, 8 GB ram, Xeon  E3-1271
* Operating system (and distribution, if any):
CentOS 7

# Bug Report

* Expected Behavior
iperf should be able to handle that window size

* Actual Behavior
iperf throws an error when window size is greater than 416k
* Steps to Reproduce
Try to do an iperf test with a window size greater than 416k

**Comment by bmah888** [comment]
I thought I had written a response to this but I didn't, apparently.

You might want to try increasing the size of `net.core.wmem_max`, which still seems to have a fairly low/default value.

Some other tips on tuning a Linux kernel (which covers setting the socket buffer sizes) can be found here:

http://fasterdata.es.net/host-tuning/linux/

Finally you may want to consider using a newer version of iperf3 (iperf 3.6 is current as of this writing). If I remember correctly, some newer versions have some fixes in the socket buffer setting code, although offhand, I remember whether they are directly applicable to this problem.

**Comment by arainero** [comment]
That's a good read, thanks.

**Comment by bmah888** [comment]
Closing this issue as I think the question was resolved.

**Comment by julben** [comment]
I still have the same problem with iperf 3.9 (on both machines):

```
$ iperf3 -c 192.168.1.100 -P 16 -w 1M
Connecting to host 192.168.1.100, port 5201
iperf3: error - socket buffer size not set correctly

$ iperf3 -c 192.168.1.100 -P 16 -w 512k
Connecting to host 192.168.1.100, port 5201
iperf3: error - socket buffer size not set correctly

$ iperf3 -c 192.168.1.100 -P 16 -w 128k
Connecting to host 192.168.1.100, port 5201
[  5] local 192.168.1.10 port 57812 connected to 192.168.1.100 port 5201
[  7] local 192.168.1.10 port 57814 connected to 192.168.1.100 port 5201
[  9] local 192.168.1.10 port 57816 connected to 192.168.1.100 port 5201
[ 11] local 192.168.1.10 port 57818 connected to 192.168.1.100 port 5201
```
I might be missing something though.

**Comment by evandrocoan** [comment]
> You might want to try increasing the size of `net.core.wmem_max`, which still seems to have a fairly low/default value.

Just remembering, you need to change this on the server and the client.
```
sudo sysctl -w net.core.wmem_max=166777216
sudo sysctl -w net.core.rmem_max=166777216
```
